### ISSUE TITLE
Any Doc or Sample Code ?

### ISSUE THREAD

**Issue by skrew** [umobi/UICreator#1]
Any Doc or Sample Code ?

Thanks

**Comment by o-nnerb** [comment]
I published the sample that I use to test. Since the alpha version is not ready, my sample can be redone using some of the latest features developed in this repository.

https://github.com/brennobemoura/UICreator-Examples

**Comment by skrew** [comment]
Thanks

FYI, It don't works, i will look later

```
/Users/<hidden>/Downloads/UICreator-Examples/Teste1/ListView.swift:121:17: error: use of unresolved identifier 'Header'
                Header {
                ^~~~~~
/Users/<hidden>/Downloads/UICreator-Examples/Teste1/ListView.swift:128:21: error: use of unresolved identifier 'Row'
                    Row {
                    ^~~

/Users/<hidden>/Downloads/UICreator-Examples/Teste1/AnimatedView.swift:58:27: error: 'radius' is inaccessible due to 'internal' protection level
                self.view.radius = (CGFloat(self.roundCount) / 6) * 0.5
                          ^~~~~~
```

**Comment by o-nnerb** [comment]
I've just committed a new version, I removed the code that isn't published yet

**Comment by skrew** [comment]
Yes it works now.
Look like a very nice project and in an (very) advanced state.
I think it's the closest syntax to swiftUI I've ever seen :)

BTW, aren't you afraid about collision between your lib / other code ?

Class name like Label(), View() (...) are too common (and will directly collide with swiftUI ?)

What do you think about add a prefix or, like SnapKit that you use, a "prefix domain" ? Something like UICView() or UIC.View() ? 
Just a suggestion ;)

I will try to add it on a (big) project and test if all running fine. I'll tell you how it went.

**Comment by o-nnerb** [comment]
Thanks for this suggestion, since SwiftUI can be used to render UICreator's view the class name conflicts may appear. I will add in the next version the UIC prefix, that will works.

Now with ForEach statement, I am developing the data management that affects directly reusable views, like when it is used in table views. In the actual version, the body is only rendered when the view will move to superview, so in init, it can't configure your subviews. It will always have to add the function .onInTheScene at init to set the data to subviews.

**Comment by skrew** [comment]
Good news (at least for me :p), i have added it to my projet (tvOS), it works fine (even on tvOS)

I will use it first with table view, so as i understand, i have to wait for the data management.

Keep up ! 👍

**Comment by o-nnerb** [comment]
Yeah! Thanks. You can use the data source to populate your views as an example in ListView.swift file, but this may change in future versions.

**Comment by skrew** [comment]
Look good for me, i will start to use it now for the current dev version and tell you if i got any problem.

Thanks again !
