### ISSUE TITLE
Question about access

### ISSUE THREAD

**Issue by skrew** [umobi/UICreator#5]
Hi,

As i can see, the lib is near (or already) mature ? Congrats !

I have a question:

Is there a way to access / assign to an UI object, like an UILabel ?
I'm using a declarative UI lib where you can assign an object, like:

```
let myLabel: UILabel!

(...)

view = LMScrollView(isFitToWidth: true,
    backgroundColor: UIColor.white,
    UILabel(text: "Hello World", textAlignment: .center) { self.myLabel = $0 } 
)
```
 
If it's not possible, how access to UI objects created ? Is it the same as swiftUI ?

Thanks

**Comment by o-nnerb** [comment]
Hi, there are three ways to access the ui object.

The first way, indirectly, is using the onNotRendered(_:), onRendered(_:) and onInTheScene(_:) methods. They all pass as parameter to the callback the UIView associated to the UIViewCreator.

```
class ContentView: UICView {

    var body: ViewCreator {
        UICLabel(”Hello World!”)
            .onNotRendered {
                ($0 as? UILabel)?.textColor = .black
            }
    }
}
```

The second way, directly, is using the UICOutlet<UIView> type that is set with as(_:) method.

```
class ContentView: UICView {
    @UICOutler var titleLabel: UILabel!

    var body: ViewCreator {
        UICLabel(”Hello World!”)
            .as(self.$titleLabel)
    }
}
```

The third way, not recommended, is using the UIViewWrapper(_:), that will expose the uiView getter.

**Comment by skrew** [comment]
Second way look fine to me.

So you confirm is not handled like SwiftUI ? (EG: adding an object to a list will automatically call the redraw of body)

**Comment by o-nnerb** [comment]
No, will not call body again.

On a list, the only case that the view will be redrawn is when the view is inside the UICForEach.

**Comment by skrew** [comment]
Great ! Thanks again ;)
