### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by skrew** [umobi/UICreator#6]
Hi,

- Is there a way to use some "dynamics" properties for layouting a view ? Like a position or size ? Something like `Relay` ? It's maybe something to do with `dynamicProperty(_:)` ?
- It will be fine to have a "facilities" to add a `UIView` to a `UICView` instead of using a `UICViewRepresentable` class, which is overkill for some simple `UIView` to add
- Do you have a "how to use" for `dynamicProperty(_:)` ? It will be fine to update the sample code with some features 

BTW, thanks ! :)

**Comment by o-nnerb** [comment]
Hi! You're welcome 😉

* Dynamic properties are a Relay object when accessed with the `$`. So, you can use the methods `next(_:)` or `sync(_:)` to update anything in your application when the view's property changes. There are a few properties available, but if some are missing please feel free to tell us.

* About using the UICViewRepresentable, I was checking in the repo today and didn't realize that there is a class, the UICContainer, that allows us to add a UIViewController directly inside the UICView.body. I will commit on develop branch adding the UICContainerView. If you want to start using now, you just need to add this class:
```
class ContainerView: UICViewRepresentable {
    let content: () -> UIView

    init(_ content: () -> UIView) {
        self.content = content
    }
    
    func makeUIView() -> UIView {
        self.content()
    }

    func updateView(_ view: UIView) {}
}
```

* As requested, I updated the UICreator-Examples with the latest features. But I will add here a short example:

```
class NumberView: UICView {
    @Property(\.sizeCategory) var sizeCategory
    let number: Int

    init(_ number: Int) {
        self.number = number
    }

    var body: ViewCreator {
        UICHStack(spacing: 7.5) {
            UICLabel("Number:")
                .font(.body)
                .vertical(hugging: .defaultHigh, compression: .required)

            UICLabel("\(self.number)")
                .font(.body)
                .vertical(hugging: .defaultHigh, compression: .required)
                .horizontal(hugging: .defaultHigh, compression: .required)
        }
        .axis(self.$sizeCategory.map { $0 >= .accessibilityMedium ? .vertical : .horizontal }
        .dynamicProperty(self._sizeCategory)
    }
}
```

**Comment by skrew** [comment]
Thanks, it's clear now.

* Another question, when i add the lib with SPM, the preview doesn't works. 
I have added `UICREATOR_SUIPREVIEWS` in the compiler flag, but it don't seem to works with a SPM package.

```Cannot find 'LivePreview' in scope```

* I would like to use a `UICView` as a `headerView` on a `UITableViewController` but it seem there are not method to get an `UIView` from an `UICView` ?

**Comment by o-nnerb** [comment]
- The LivePreview was removed because the compiler was trowing some errors at compilation time. So, you need to implement your own LivePreview using the SwiftUI.UIViewControllerRepresentable that will wrap the UICreator.UICHostingController.

- To use any ViewCreator objects as UIViewController or UIView, you will need the UICHostingController class or implement a generic UIView class that will add the UICHostingController instance at didMoveToWindow(), by calling the methods addChild(_:) and willMove(toParent:). If you don't want to implement anything, you can use the UICHostingView, but this class can be removed in the future.

**Comment by skrew** [comment]
Ok thanks for all ;)
